services:
  - type: web
    name: logo-generator-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PORT
        value: 10000

